/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vst.Alquiler;

import Vst.Alquiler.*;

/**
 *
 * @author admin
 */
public class VstAlquiler_Lista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Vuelos1
     */
    public VstAlquiler_Lista() {
        initComponents();
        
        //agregando opciones al combo de estado de alquiler
         cmbEstadoAlquiler.addItem("-");
        cmbEstadoAlquiler.addItem("EN PROCESO");
        cmbEstadoAlquiler.addItem("FINALIZADO");
        cmbEstadoAlquiler.addItem("ANULADO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarVuelos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnAlquiler_Nvo = new javax.swing.JButton();
        jbtnEditarHerramienta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlquileres = new javax.swing.JTable();
        btnAlquiler_Buscar = new javax.swing.JButton();
        lblAlquiler_Nro = new javax.swing.JLabel();
        cmbEstadoAlquiler = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAlquiler_Devolucion = new javax.swing.JButton();
        jbtnReiniciar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1121, 784));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPestañaAdministrarVuelos.setBackground(new java.awt.Color(27, 23, 51));
        jpnlPestañaAdministrarVuelos.setMinimumSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarVuelos.setPreferredSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarVuelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(30, 151, 196));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTRO DE ALQUILERES");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        jpnlPestañaAdministrarVuelos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1090, 30));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarVuelos.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1090, 10));

        btnAlquiler_Nvo.setBackground(new java.awt.Color(102, 0, 51));
        btnAlquiler_Nvo.setForeground(new java.awt.Color(255, 255, 255));
        btnAlquiler_Nvo.setText("NUEVO ALQUILER");
        jpnlPestañaAdministrarVuelos.add(btnAlquiler_Nvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 150, 40));

        jbtnEditarHerramienta.setBackground(new java.awt.Color(102, 0, 51));
        jbtnEditarHerramienta.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEditarHerramienta.setText("EDITAR");
        jpnlPestañaAdministrarVuelos.add(jbtnEditarHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 120, 40));

        tblAlquileres.setBackground(new java.awt.Color(217, 217, 217));
        tblAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlquileres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlquileresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAlquileres);

        jpnlPestañaAdministrarVuelos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1090, 560));

        btnAlquiler_Buscar.setBackground(new java.awt.Color(153, 0, 0));
        btnAlquiler_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar 24x24.png"))); // NOI18N
        jpnlPestañaAdministrarVuelos.add(btnAlquiler_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 60, 40));

        lblAlquiler_Nro.setBackground(new java.awt.Color(102, 0, 51));
        lblAlquiler_Nro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlquiler_Nro.setForeground(new java.awt.Color(255, 255, 255));
        lblAlquiler_Nro.setText("Numero de Registros: ");
        lblAlquiler_Nro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnlPestañaAdministrarVuelos.add(lblAlquiler_Nro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 695, 220, 40));

        cmbEstadoAlquiler.setBackground(new java.awt.Color(217, 217, 217));
        jpnlPestañaAdministrarVuelos.add(cmbEstadoAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ESTADO");
        jpnlPestañaAdministrarVuelos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, -1));

        btnAlquiler_Devolucion.setBackground(new java.awt.Color(102, 0, 51));
        btnAlquiler_Devolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnAlquiler_Devolucion.setText("DEVOLUCION");
        jpnlPestañaAdministrarVuelos.add(btnAlquiler_Devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 130, 40));

        jbtnReiniciar.setBackground(new java.awt.Color(0, 102, 153));
        jbtnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReiniciar.setText("Actualizar lista");
        jpnlPestañaAdministrarVuelos.add(jbtnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 150, 40));

        getContentPane().add(jpnlPestañaAdministrarVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAlquileresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlquileresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlquileresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlquiler_Buscar;
    public javax.swing.JButton btnAlquiler_Devolucion;
    public javax.swing.JButton btnAlquiler_Nvo;
    public javax.swing.JComboBox<String> cmbEstadoAlquiler;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtnEditarHerramienta;
    public javax.swing.JButton jbtnReiniciar;
    private javax.swing.JPanel jpnlPestañaAdministrarVuelos;
    public javax.swing.JLabel lblAlquiler_Nro;
    public javax.swing.JTable tblAlquileres;
    // End of variables declaration//GEN-END:variables
}
