/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vst.Alquiler;

import Vst.Herramienta.*;
import java.awt.Color;

/**
 *
 * @author User
 */
public class VstAlquiler_Devolver extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLibroNuevo
     */
    public VstAlquiler_Devolver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumBoleta = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtNomCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsDevol = new javax.swing.JTextArea();
        txtImp_Alq = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtImp_Transp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtClienteCom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtImpDevol = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtFecDevol = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtAnioFabrica1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtImp_Garant = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtFecRetiro = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Herramienta Nueva");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 23, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Devolver Alquiler", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N° Boleta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, -1));

        txtNumBoleta.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.add(txtNumBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 140, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 120, 50));

        txtNomCli.setBackground(new java.awt.Color(217, 217, 217));
        txtNomCli.setForeground(new java.awt.Color(153, 153, 153));
        txtNomCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNomCliMousePressed(evt);
            }
        });
        txtNomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomCliActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 320, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id alquiler:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Observaciones:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, -1));

        txtObsDevol.setBackground(new java.awt.Color(217, 217, 217));
        txtObsDevol.setColumns(20);
        txtObsDevol.setRows(5);
        txtObsDevol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtObsDevol);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 330, 90));

        txtImp_Alq.setBackground(new java.awt.Color(217, 217, 217));
        txtImp_Alq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImp_AlqKeyPressed(evt);
            }
        });
        jPanel1.add(txtImp_Alq, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 140, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Importe Alquiler:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Importe Transporte:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 130, -1));

        txtImp_Transp.setBackground(new java.awt.Color(217, 217, 217));
        txtImp_Transp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImp_TranspKeyPressed(evt);
            }
        });
        jPanel1.add(txtImp_Transp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Devolución:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 130, 20));

        txtClienteCom.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.add(txtClienteCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Importe Devolución:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 130, -1));

        txtImpDevol.setBackground(new java.awt.Color(217, 217, 217));
        txtImpDevol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpDevolActionPerformed(evt);
            }
        });
        jPanel1.add(txtImpDevol, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 140, 40));

        btnGuardar.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 120, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 150, 10));

        txtFecDevol.setDateFormatString("yyyy-MM-dd");
        txtFecDevol.setMaxSelectableDate(new java.util.Date(253370786512000L));
        txtFecDevol.setMinSelectableDate(new java.util.Date(-2208966572000L));
        txtFecDevol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFecDevolMousePressed(evt);
            }
        });
        jPanel1.add(txtFecDevol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Importe Transporte:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 130, -1));

        txtAnioFabrica1.setBackground(new java.awt.Color(217, 217, 217));
        txtAnioFabrica1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnioFabrica1KeyPressed(evt);
            }
        });
        jPanel1.add(txtAnioFabrica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Importe Garantía:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 130, -1));

        txtImp_Garant.setBackground(new java.awt.Color(217, 217, 217));
        txtImp_Garant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImp_GarantKeyPressed(evt);
            }
        });
        jPanel1.add(txtImp_Garant, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, 40));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 10, 330));

        txtFecRetiro.setDateFormatString("yyyy-MM-dd");
        txtFecRetiro.setMaxSelectableDate(new java.util.Date(253370786512000L));
        txtFecRetiro.setMinSelectableDate(new java.util.Date(-2208966572000L));
        txtFecRetiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFecRetiroMousePressed(evt);
            }
        });
        jPanel1.add(txtFecRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha Retiro:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomCliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomCliMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomCliMousePressed

    private void txtNomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomCliActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtImp_TranspKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImp_TranspKeyPressed
        // TODO add your handling code here:
        
        //para que solo acepte números
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtImp_TranspKeyPressed

    private void txtImp_AlqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImp_AlqKeyPressed
        // TODO add your handling code here:
        
        //para que acepte decimales
        char c=evt.getKeyChar();
        if(Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }               
        
//        try{
//            Double.parseDouble(txtPeso.getText()+evt.getKeyChar());
//        }catch(NumberFormatException e){
//            evt.consume();
//        }
    }//GEN-LAST:event_txtImp_AlqKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtFecDevolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFecDevolMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecDevolMousePressed

    private void txtAnioFabrica1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioFabrica1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioFabrica1KeyPressed

    private void txtImp_GarantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImp_GarantKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImp_GarantKeyPressed

    private void txtFecRetiroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFecRetiroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecRetiroMousePressed

    private void txtImpDevolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpDevolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpDevolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstAlquiler_Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstAlquiler_Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstAlquiler_Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstAlquiler_Devolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstAlquiler_Devolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtAnioFabrica1;
    public javax.swing.JTextField txtClienteCom;
    public com.toedter.calendar.JDateChooser txtFecDevol;
    public com.toedter.calendar.JDateChooser txtFecRetiro;
    public javax.swing.JTextField txtImpDevol;
    public javax.swing.JTextField txtImp_Alq;
    public javax.swing.JTextField txtImp_Garant;
    public javax.swing.JTextField txtImp_Transp;
    public javax.swing.JTextField txtNomCli;
    public javax.swing.JTextField txtNumBoleta;
    public javax.swing.JTextArea txtObsDevol;
    // End of variables declaration//GEN-END:variables
}
