/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vst.Tipo;

/**
 *
 * @author admin
 */
public class VstTipo_Lista extends javax.swing.JInternalFrame {

    /**
     * Creates new form prueba
     */
    public VstTipo_Lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarUsuarios = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscarPorID = new javax.swing.JTextField();
        jbtnAgregarTipo = new javax.swing.JButton();
        jbtnEditarTipo = new javax.swing.JButton();
        jbtnBuscarTipo = new javax.swing.JButton();
        jlblRegistros = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        setPreferredSize(new java.awt.Dimension(1121, 784));

        jpnlPestañaAdministrarUsuarios.setBackground(new java.awt.Color(27, 23, 51));
        jpnlPestañaAdministrarUsuarios.setPreferredSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 0, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTRO DE TIPOS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 30));

        jpnlPestañaAdministrarUsuarios.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1080, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarUsuarios.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1080, 10));

        jtblDatos.setBackground(new java.awt.Color(217, 217, 217));
        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos);

        jpnlPestañaAdministrarUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1070, 560));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CODIGO");
        jpnlPestañaAdministrarUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jtxtBuscarPorID.setBackground(new java.awt.Color(217, 217, 217));
        jpnlPestañaAdministrarUsuarios.add(jtxtBuscarPorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        jbtnAgregarTipo.setBackground(new java.awt.Color(102, 0, 51));
        jbtnAgregarTipo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarTipo.setText("Añadir");
        jbtnAgregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarTipoActionPerformed(evt);
            }
        });
        jpnlPestañaAdministrarUsuarios.add(jbtnAgregarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 100, 40));

        jbtnEditarTipo.setBackground(new java.awt.Color(102, 0, 51));
        jbtnEditarTipo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEditarTipo.setText("Editar");
        jpnlPestañaAdministrarUsuarios.add(jbtnEditarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 100, 40));

        jbtnBuscarTipo.setBackground(new java.awt.Color(102, 0, 51));
        jbtnBuscarTipo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBuscarTipo.setText("Buscar");
        jpnlPestañaAdministrarUsuarios.add(jbtnBuscarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 100, 40));

        jlblRegistros.setBackground(new java.awt.Color(102, 0, 51));
        jlblRegistros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblRegistros.setForeground(new java.awt.Color(255, 255, 255));
        jlblRegistros.setText("Numero de Registros: ");
        jlblRegistros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnlPestañaAdministrarUsuarios.add(jlblRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnlPestañaAdministrarUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnlPestañaAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAgregarTipo;
    public javax.swing.JButton jbtnBuscarTipo;
    public javax.swing.JButton jbtnEditarTipo;
    public javax.swing.JLabel jlblRegistros;
    public javax.swing.JPanel jpnlPestañaAdministrarUsuarios;
    public javax.swing.JTable jtblDatos;
    public javax.swing.JTextField jtxtBuscarPorID;
    // End of variables declaration//GEN-END:variables
}
