/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vst.Empleado;

/**
 *
 * @author admin
 */
public class VstEmpleado_Lista extends javax.swing.JInternalFrame {

    /**
     * Creates new form prueba
     */
    public VstEmpleado_Lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarUsuarios = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos_Usuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscarPorDni = new javax.swing.JTextField();
        jbtnAgregarUsuario = new javax.swing.JButton();
        jlblRegistros_Usuarios = new javax.swing.JLabel();
        jbtnBuscarUsuario = new javax.swing.JButton();
        jbtnEditarUsuario = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPestañaAdministrarUsuarios.setBackground(new java.awt.Color(27, 23, 51));
        jpnlPestañaAdministrarUsuarios.setPreferredSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 0, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTRO DE USUARIOS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        jpnlPestañaAdministrarUsuarios.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1090, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarUsuarios.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1090, 10));

        jtblDatos_Usuarios.setBackground(new java.awt.Color(217, 217, 217));
        jtblDatos_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDatos_Usuarios);

        jpnlPestañaAdministrarUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1080, 550));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" DNI: ");
        jpnlPestañaAdministrarUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jtxtBuscarPorDni.setBackground(new java.awt.Color(217, 217, 217));
        jpnlPestañaAdministrarUsuarios.add(jtxtBuscarPorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 30));

        jbtnAgregarUsuario.setBackground(new java.awt.Color(102, 0, 51));
        jbtnAgregarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarUsuario.setText("Añadir");
        jbtnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarUsuarioActionPerformed(evt);
            }
        });
        jpnlPestañaAdministrarUsuarios.add(jbtnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 110, 40));

        jlblRegistros_Usuarios.setBackground(new java.awt.Color(102, 0, 51));
        jlblRegistros_Usuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblRegistros_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        jlblRegistros_Usuarios.setText("Numero de Registros: ");
        jlblRegistros_Usuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnlPestañaAdministrarUsuarios.add(jlblRegistros_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 220, 40));

        jbtnBuscarUsuario.setBackground(new java.awt.Color(153, 0, 0));
        jbtnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar 24x24.png"))); // NOI18N
        jpnlPestañaAdministrarUsuarios.add(jbtnBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 70, 40));

        jbtnEditarUsuario.setBackground(new java.awt.Color(102, 0, 51));
        jbtnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEditarUsuario.setText("Editar");
        jpnlPestañaAdministrarUsuarios.add(jbtnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 120, 40));

        getContentPane().add(jpnlPestañaAdministrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -1, 1110, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAgregarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnAgregarUsuario;
    public javax.swing.JButton jbtnBuscarUsuario;
    public javax.swing.JButton jbtnEditarUsuario;
    public javax.swing.JLabel jlblRegistros_Usuarios;
    public javax.swing.JPanel jpnlPestañaAdministrarUsuarios;
    public javax.swing.JTable jtblDatos_Usuarios;
    public javax.swing.JTextField jtxtBuscarPorDni;
    // End of variables declaration//GEN-END:variables
}
