/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vst.Empleado;

import java.awt.Color;

/**
 *
 * @author admin
 */
public class VstEmpleado_Editar extends javax.swing.JFrame {

    /**
     * Creates new form EditarDatosUsuarios
     */
    public VstEmpleado_Editar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtEditarApellidos = new javax.swing.JTextField();
        jtxtEditarNumCelular = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbxEditarGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jtxtEditarNombres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jpswEditarIngresarContraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jpswEditarConfirmarContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jcbxEditarTipoEmpleado = new javax.swing.JComboBox<>();
        jtxtEditarCorreo = new javax.swing.JTextField();
        jtxtEditarDNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Chk_Activo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 23, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(320, 490));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 490));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtEditarApellidos.setBackground(new java.awt.Color(217, 217, 217));
        jtxtEditarApellidos.setText("Apellidos");
        jtxtEditarApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarApellidosMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 40));

        jtxtEditarNumCelular.setBackground(new java.awt.Color(217, 217, 217));
        jtxtEditarNumCelular.setText("Número de celular");
        jtxtEditarNumCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarNumCelularMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarNumCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Género:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jcbxEditarGenero.setBackground(new java.awt.Color(217, 217, 217));
        jcbxEditarGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jPanel1.add(jcbxEditarGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de nacimiento: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estado del Usuario: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 130, 50));

        jtxtEditarNombres.setBackground(new java.awt.Color(217, 217, 217));
        jtxtEditarNombres.setText("Nombres");
        jtxtEditarNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarNombresMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 40));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingresar contaseña: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, -1));

        jpswEditarIngresarContraseña.setBackground(new java.awt.Color(217, 217, 217));
        jpswEditarIngresarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpswEditarIngresarContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(jpswEditarIngresarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 40));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirmar contaseña:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, -1));

        jpswEditarConfirmarContraseña.setBackground(new java.awt.Color(217, 217, 217));
        jpswEditarConfirmarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpswEditarConfirmarContraseñaMousePressed(evt);
            }
        });
        jPanel1.add(jpswEditarConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 130, 40));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de empleado: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 130, -1));

        jcbxEditarTipoEmpleado.setBackground(new java.awt.Color(217, 217, 217));
        jcbxEditarTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "EMPLEADO" }));
        jPanel1.add(jcbxEditarTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 130, 40));

        jtxtEditarCorreo.setBackground(new java.awt.Color(217, 217, 217));
        jtxtEditarCorreo.setText("Correo Electrónico");
        jtxtEditarCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarCorreoMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 40));

        jtxtEditarDNI.setBackground(new java.awt.Color(217, 217, 217));
        jtxtEditarDNI.setText("DNI");
        jtxtEditarDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEditarDNIMousePressed(evt);
            }
        });
        jPanel1.add(jtxtEditarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, 40));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Número de celular: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correo Electrónico:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DNI: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, -1));

        Chk_Activo.setBackground(new java.awt.Color(217, 217, 217));
        Chk_Activo.setText("Activo");
        jPanel1.add(Chk_Activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtxtEditarNombresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarNombresMousePressed
        if (jtxtEditarNombres.getText().equals("Nombres")){
            jtxtEditarNombres.setText("");
            jtxtEditarNombres.setForeground(Color.BLACK);            
        }
        if (jtxtEditarApellidos.getText().equals("") || jtxtEditarApellidos.getText() == null || jtxtEditarApellidos.getText().equals(" "))
                jtxtEditarApellidos.setText("Apellidos");
            jtxtEditarApellidos.setForeground(Color.GRAY);
            if (jtxtEditarNumCelular.getText().equals("") || jtxtEditarNumCelular.getText() == null || jtxtEditarNumCelular.getText().equals(" "))
                jtxtEditarNumCelular.setText("Número de celular");
            jtxtEditarNumCelular.setForeground(Color.GRAY);
            if (jtxtEditarCorreo.getText().equals("") || jtxtEditarCorreo.getText() == null || jtxtEditarCorreo.getText().equals(" "))
                jtxtEditarCorreo.setText("Correo Electrónico");
            jtxtEditarCorreo.setForeground(Color.GRAY);
            if (jtxtEditarDNI.getText().equals("") || jtxtEditarDNI.getText() == null || jtxtEditarDNI.getText().equals(" "))
                jtxtEditarDNI.setText("DNI");
            jtxtEditarDNI.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarIngresarContraseña.getPassword()) == null || String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals(" "))
                jpswEditarIngresarContraseña.setText("**********");
            jpswEditarIngresarContraseña.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarConfirmarContraseña.getPassword()) == null || String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals(" "))
                jpswEditarConfirmarContraseña.setText("**********");
            jpswEditarConfirmarContraseña.setForeground(Color.GRAY);
    }//GEN-LAST:event_jtxtEditarNombresMousePressed

    private void jtxtEditarApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarApellidosMousePressed
        if (jtxtEditarApellidos.getText().equals("Apellidos")){
            jtxtEditarApellidos.setText("");
            jtxtEditarApellidos.setForeground(Color.BLACK);            
        }
        if (jtxtEditarNombres.getText().equals("") || jtxtEditarNombres.getText() == null || jtxtEditarNombres.getText().equals(" "))
                jtxtEditarNombres.setText("Nombres");
            jtxtEditarNombres.setForeground(Color.GRAY);
            if (jtxtEditarNumCelular.getText().equals("") || jtxtEditarNumCelular.getText() == null || jtxtEditarNumCelular.getText().equals(" "))
                jtxtEditarNumCelular.setText("Número de celular");
            jtxtEditarNumCelular.setForeground(Color.GRAY);
            if (jtxtEditarCorreo.getText().equals("") || jtxtEditarCorreo.getText() == null || jtxtEditarCorreo.getText().equals(" "))
                jtxtEditarCorreo.setText("Correo Electrónico");
            jtxtEditarCorreo.setForeground(Color.GRAY);
            if (jtxtEditarDNI.getText().equals("") || jtxtEditarDNI.getText() == null || jtxtEditarDNI.getText().equals(" "))
                jtxtEditarDNI.setText("DNI");
            jtxtEditarDNI.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarIngresarContraseña.getPassword()) == null || String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals(" "))
                jpswEditarIngresarContraseña.setText("**********");
            jpswEditarIngresarContraseña.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarConfirmarContraseña.getPassword()) == null || String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals(" "))
                jpswEditarConfirmarContraseña.setText("**********");
            jpswEditarConfirmarContraseña.setForeground(Color.GRAY);
    }//GEN-LAST:event_jtxtEditarApellidosMousePressed

    private void jtxtEditarNumCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarNumCelularMousePressed
        if (jtxtEditarNumCelular.getText().equals("Número de celular")){
            jtxtEditarNumCelular.setText("");
            jtxtEditarNumCelular.setForeground(Color.BLACK);            
        }
        if (jtxtEditarNombres.getText().equals("") || jtxtEditarNombres.getText() == null || jtxtEditarNombres.getText().equals(" "))
                jtxtEditarNombres.setText("Nombres");
            jtxtEditarNombres.setForeground(Color.GRAY);
            if (jtxtEditarApellidos.getText().equals("") || jtxtEditarApellidos.getText() == null || jtxtEditarApellidos.getText().equals(" "))
                jtxtEditarApellidos.setText("Apellidos");
            jtxtEditarApellidos.setForeground(Color.GRAY);
            if (jtxtEditarCorreo.getText().equals("") || jtxtEditarCorreo.getText() == null || jtxtEditarCorreo.getText().equals(" "))
                jtxtEditarCorreo.setText("Correo Electrónico");
            jtxtEditarCorreo.setForeground(Color.GRAY);
            if (jtxtEditarDNI.getText().equals("") || jtxtEditarDNI.getText() == null || jtxtEditarDNI.getText().equals(" "))
                jtxtEditarDNI.setText("DNI");
            jtxtEditarDNI.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarIngresarContraseña.getPassword()) == null || String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals(" "))
                jpswEditarIngresarContraseña.setText("**********");
            jpswEditarIngresarContraseña.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarConfirmarContraseña.getPassword()) == null || String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals(" "))
                jpswEditarConfirmarContraseña.setText("**********");
            jpswEditarConfirmarContraseña.setForeground(Color.GRAY);
    }//GEN-LAST:event_jtxtEditarNumCelularMousePressed

    private void jpswEditarIngresarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpswEditarIngresarContraseñaMousePressed
        if (String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals("**********")){
            jpswEditarIngresarContraseña.setText("");
            jpswEditarIngresarContraseña.setForeground(Color.BLACK);
        }
        if (jtxtEditarNombres.getText().equals("") || jtxtEditarNombres.getText() == null || jtxtEditarNombres.getText().equals(" "))
                jtxtEditarNombres.setText("Nombres");
            jtxtEditarNombres.setForeground(Color.GRAY);
            if (jtxtEditarApellidos.getText().equals("") || jtxtEditarApellidos.getText() == null || jtxtEditarApellidos.getText().equals(" "))
                jtxtEditarApellidos.setText("Apellidos");
            jtxtEditarApellidos.setForeground(Color.GRAY);
            if (jtxtEditarNumCelular.getText().equals("") || jtxtEditarNumCelular.getText() == null || jtxtEditarNumCelular.getText().equals(" "))
                jtxtEditarNumCelular.setText("Número de celular");
            jtxtEditarNumCelular.setForeground(Color.GRAY);
            if (jtxtEditarCorreo.getText().equals("") || jtxtEditarCorreo.getText() == null || jtxtEditarCorreo.getText().equals(" "))
                jtxtEditarCorreo.setText("Correo Electrónico");
            jtxtEditarCorreo.setForeground(Color.GRAY);
            if (jtxtEditarDNI.getText().equals("") || jtxtEditarDNI.getText() == null || jtxtEditarDNI.getText().equals(" "))
                jtxtEditarDNI.setText("DNI");
            jtxtEditarDNI.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarConfirmarContraseña.getPassword()) == null || String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals(" "))
                jpswEditarConfirmarContraseña.setText("**********");
            jpswEditarConfirmarContraseña.setForeground(Color.GRAY);
    }//GEN-LAST:event_jpswEditarIngresarContraseñaMousePressed

    private void jpswEditarConfirmarContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpswEditarConfirmarContraseñaMousePressed
        if (String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals("**********")){
            jpswEditarConfirmarContraseña.setText("");
            jpswEditarConfirmarContraseña.setForeground(Color.BLACK);
        }
        if (jtxtEditarNombres.getText().equals("") || jtxtEditarNombres.getText() == null || jtxtEditarNombres.getText().equals(" "))
                jtxtEditarNombres.setText("Nombres");
            jtxtEditarNombres.setForeground(Color.GRAY);
            if (jtxtEditarApellidos.getText().equals("") || jtxtEditarApellidos.getText() == null || jtxtEditarApellidos.getText().equals(" "))
                jtxtEditarApellidos.setText("Apellidos");
            jtxtEditarApellidos.setForeground(Color.GRAY);
            if (jtxtEditarNumCelular.getText().equals("") || jtxtEditarNumCelular.getText() == null || jtxtEditarNumCelular.getText().equals(" "))
                jtxtEditarNumCelular.setText("Número de celular");
            jtxtEditarNumCelular.setForeground(Color.GRAY);
            if (jtxtEditarCorreo.getText().equals("") || jtxtEditarCorreo.getText() == null || jtxtEditarCorreo.getText().equals(" "))
                jtxtEditarCorreo.setText("Correo Electrónico");
            jtxtEditarCorreo.setForeground(Color.GRAY);
            if (jtxtEditarDNI.getText().equals("") || jtxtEditarDNI.getText() == null || jtxtEditarDNI.getText().equals(" "))
                jtxtEditarDNI.setText("DNI");
            jtxtEditarDNI.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarIngresarContraseña.getPassword()) == null || String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals(" "))
                jpswEditarIngresarContraseña.setText("**********");
            jpswEditarIngresarContraseña.setForeground(Color.GRAY);
    }//GEN-LAST:event_jpswEditarConfirmarContraseñaMousePressed

    private void jtxtEditarCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarCorreoMousePressed
        if (jtxtEditarCorreo.getText().equals("Correo Electrónico")){
            jtxtEditarCorreo.setText("");
            jtxtEditarCorreo.setForeground(Color.BLACK);
        }
        if (jtxtEditarNombres.getText().equals("") || jtxtEditarNombres.getText() == null || jtxtEditarNombres.getText().equals(" "))
                jtxtEditarNombres.setText("Nombres");
            jtxtEditarNombres.setForeground(Color.GRAY);
            if (jtxtEditarApellidos.getText().equals("") || jtxtEditarApellidos.getText() == null || jtxtEditarApellidos.getText().equals(" "))
                jtxtEditarApellidos.setText("Apellidos");
            jtxtEditarApellidos.setForeground(Color.GRAY);
            if (jtxtEditarNumCelular.getText().equals("") || jtxtEditarNumCelular.getText() == null || jtxtEditarNumCelular.getText().equals(" "))
                jtxtEditarNumCelular.setText("Número de celular");
            jtxtEditarNumCelular.setForeground(Color.GRAY);
            if (jtxtEditarDNI.getText().equals("") || jtxtEditarDNI.getText() == null || jtxtEditarDNI.getText().equals(" "))
                jtxtEditarDNI.setText("DNI");
            jtxtEditarDNI.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarIngresarContraseña.getPassword()) == null || String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals(" "))
                jpswEditarIngresarContraseña.setText("**********");
            jpswEditarIngresarContraseña.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarConfirmarContraseña.getPassword()) == null || String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals(" "))
                jpswEditarConfirmarContraseña.setText("**********");
            jpswEditarConfirmarContraseña.setForeground(Color.GRAY);
    }//GEN-LAST:event_jtxtEditarCorreoMousePressed

    private void jtxtEditarDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEditarDNIMousePressed
        if (jtxtEditarDNI.getText().equals("DNI")){
            jtxtEditarDNI.setText("");
            jtxtEditarDNI.setForeground(Color.BLACK);
        }
        if (jtxtEditarNombres.getText().equals("") || jtxtEditarNombres.getText() == null || jtxtEditarNombres.getText().equals(" "))
                jtxtEditarNombres.setText("Nombres");
            jtxtEditarNombres.setForeground(Color.GRAY);
            if (jtxtEditarApellidos.getText().equals("") || jtxtEditarApellidos.getText() == null || jtxtEditarApellidos.getText().equals(" "))
                jtxtEditarApellidos.setText("Apellidos");
            jtxtEditarApellidos.setForeground(Color.GRAY);
            if (jtxtEditarNumCelular.getText().equals("") || jtxtEditarNumCelular.getText() == null || jtxtEditarNumCelular.getText().equals(" "))
                jtxtEditarNumCelular.setText("Número de celular");
            jtxtEditarNumCelular.setForeground(Color.GRAY);
            if (jtxtEditarCorreo.getText().equals("") || jtxtEditarCorreo.getText() == null || jtxtEditarCorreo.getText().equals(" "))
                jtxtEditarCorreo.setText("Correo Electrónico");
            jtxtEditarCorreo.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarIngresarContraseña.getPassword()) == null || String.valueOf(jpswEditarIngresarContraseña.getPassword()).equals(" "))
                jpswEditarIngresarContraseña.setText("**********");
            jpswEditarIngresarContraseña.setForeground(Color.GRAY);
            if (String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals("") || String.valueOf(jpswEditarConfirmarContraseña.getPassword()) == null || String.valueOf(jpswEditarConfirmarContraseña.getPassword()).equals(" "))
                jpswEditarConfirmarContraseña.setText("**********");
            jpswEditarConfirmarContraseña.setForeground(Color.GRAY);
    }//GEN-LAST:event_jtxtEditarDNIMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstEmpleado_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstEmpleado_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstEmpleado_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstEmpleado_Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstEmpleado_Editar().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox Chk_Activo;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> jcbxEditarGenero;
    public javax.swing.JComboBox<String> jcbxEditarTipoEmpleado;
    public javax.swing.JPasswordField jpswEditarConfirmarContraseña;
    public javax.swing.JPasswordField jpswEditarIngresarContraseña;
    public javax.swing.JTextField jtxtEditarApellidos;
    public javax.swing.JTextField jtxtEditarCorreo;
    public javax.swing.JTextField jtxtEditarDNI;
    public javax.swing.JTextField jtxtEditarNombres;
    public javax.swing.JTextField jtxtEditarNumCelular;
    // End of variables declaration//GEN-END:variables
}
