/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vst.Recibo;

/**
 *
 * @author admin
 */
public class VstAdminHistoFac extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Cliente2
     */
    public VstAdminHistoFac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarClientes = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelCliente = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jbtnBuscarClienteDNI = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblHistorial_Libros_Cliente = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtxaDatosCliente = new javax.swing.JTextArea();
        jtxtBuscarClienteDNI = new javax.swing.JTextField();
        jPanelEmpresa = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jbtnBuscarClienteRUC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHistorial_Libros_Cliente_Empresa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtxaDatosEmpresa = new javax.swing.JTextArea();
        jtxtBuscarEmpresaRUC = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPestañaAdministrarClientes.setBackground(new java.awt.Color(255, 255, 255));
        jpnlPestañaAdministrarClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarClientes.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1080, 10));

        jTabbedPane2.setBackground(new java.awt.Color(27, 23, 51));

        jPanelCliente.setBackground(new java.awt.Color(27, 23, 51));
        jPanelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DNI");
        jPanelCliente.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jbtnBuscarClienteDNI.setBackground(new java.awt.Color(153, 0, 0));
        jbtnBuscarClienteDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar 24x24.png"))); // NOI18N
        jPanelCliente.add(jbtnBuscarClienteDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, 40));

        jtblHistorial_Libros_Cliente.setBackground(new java.awt.Color(217, 217, 217));
        jtblHistorial_Libros_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblHistorial_Libros_Cliente);

        jPanelCliente.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 710, 580));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HISTORIAL");
        jPanelCliente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 160, 20));

        jtxaDatosCliente.setEditable(false);
        jtxaDatosCliente.setBackground(new java.awt.Color(217, 217, 217));
        jtxaDatosCliente.setColumns(20);
        jtxaDatosCliente.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxaDatosCliente.setRows(5);
        jtxaDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos De La Persona", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jScrollPane10.setViewportView(jtxaDatosCliente);

        jPanelCliente.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 540));

        jtxtBuscarClienteDNI.setBackground(new java.awt.Color(217, 217, 217));
        jPanelCliente.add(jtxtBuscarClienteDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        jTabbedPane2.addTab("CLIENTE", jPanelCliente);

        jPanelEmpresa.setBackground(new java.awt.Color(27, 23, 51));
        jPanelEmpresa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("RUC");
        jPanelEmpresa.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jbtnBuscarClienteRUC.setBackground(new java.awt.Color(153, 0, 0));
        jbtnBuscarClienteRUC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar 24x24.png"))); // NOI18N
        jPanelEmpresa.add(jbtnBuscarClienteRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, 40));

        jtblHistorial_Libros_Cliente_Empresa.setBackground(new java.awt.Color(217, 217, 217));
        jtblHistorial_Libros_Cliente_Empresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblHistorial_Libros_Cliente_Empresa);

        jPanelEmpresa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 710, 580));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HISTORIAL");
        jPanelEmpresa.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 160, 20));

        jtxaDatosEmpresa.setEditable(false);
        jtxaDatosEmpresa.setBackground(new java.awt.Color(217, 217, 217));
        jtxaDatosEmpresa.setColumns(20);
        jtxaDatosEmpresa.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxaDatosEmpresa.setRows(5);
        jtxaDatosEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos De La Empresa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jScrollPane11.setViewportView(jtxaDatosEmpresa);

        jPanelEmpresa.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 540));

        jtxtBuscarEmpresaRUC.setBackground(new java.awt.Color(217, 217, 217));
        jPanelEmpresa.add(jtxtBuscarEmpresaRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        jTabbedPane2.addTab("EMPRESA", jPanelEmpresa);

        jpnlPestañaAdministrarClientes.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1080, 670));

        jPanel13.setBackground(new java.awt.Color(51, 0, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("REGISTRO DE FACTURAS");
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 30));

        jpnlPestañaAdministrarClientes.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1080, 30));

        getContentPane().add(jpnlPestañaAdministrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 1105, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JButton jbtnBuscarClienteDNI;
    public javax.swing.JButton jbtnBuscarClienteRUC;
    private javax.swing.JPanel jpnlPestañaAdministrarClientes;
    public javax.swing.JTable jtblHistorial_Libros_Cliente;
    public javax.swing.JTable jtblHistorial_Libros_Cliente_Empresa;
    public javax.swing.JTextArea jtxaDatosCliente;
    public javax.swing.JTextArea jtxaDatosEmpresa;
    public javax.swing.JTextField jtxtBuscarClienteDNI;
    public javax.swing.JTextField jtxtBuscarEmpresaRUC;
    // End of variables declaration//GEN-END:variables
}
