/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vst.Recibo;

/**
 *
 * @author carra
 */
public class VstReciboVista1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Recibos
     */
    public VstReciboVista1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnImprimir = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxaRecibo = new javax.swing.JTextArea();
        jbtnRegresarABuscarLibro = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 23, 51));
        setPreferredSize(new java.awt.Dimension(1121, 784));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnImprimir.setText("Imprimir");
        getContentPane().add(jbtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 690, 140, 30));

        jPanel16.setBackground(new java.awt.Color(51, 0, 51));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setBackground(new java.awt.Color(51, 0, 51));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("BOLETO Y RECIBO");
        jPanel16.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1090, 30));

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1090, 10));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("¡GRACIAS POR CONFIAR EN ");
        jPanel12.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("VOLTEA LA PÁGINA!");
        jPanel12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, -1));

        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("o((>ω< ))o");
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 60, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gif Libro.gif"))); // NOI18N
        jPanel12.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 400, 220));

        jtxaRecibo.setEditable(false);
        jtxaRecibo.setBackground(new java.awt.Color(217, 217, 217));
        jtxaRecibo.setColumns(20);
        jtxaRecibo.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        jtxaRecibo.setRows(5);
        jtxaRecibo.setText("RECIBO\n\n\n\n\n\n\nAUN NO TERMINADO u.u, proyecto 95% terminado :)");
        jScrollPane5.setViewportView(jtxaRecibo);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 470, 660));

        jbtnRegresarABuscarLibro.setBackground(new java.awt.Color(0, 68, 160));
        jbtnRegresarABuscarLibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnRegresarABuscarLibro.setForeground(new java.awt.Color(204, 204, 204));
        jbtnRegresarABuscarLibro.setText("Ir a Buscar Libros");
        getContentPane().add(jbtnRegresarABuscarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 690, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JButton jbtnImprimir;
    public javax.swing.JButton jbtnRegresarABuscarLibro;
    public javax.swing.JTextArea jtxaRecibo;
    // End of variables declaration//GEN-END:variables
}
