/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vst.Mantenimiento;

import Vst.Herramienta.*;

/**
 *
 * @author admin
 */
public class VstMantenimiento_Lista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Vuelos1
     */
    public VstMantenimiento_Lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarVuelos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblTablaDeMantenimientos = new javax.swing.JTable();
        jlblNumeroDeOrdenes = new javax.swing.JLabel();
        jbtnReiniciar = new javax.swing.JButton();
        jbtnInfoOrden = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1121, 784));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPestañaAdministrarVuelos.setBackground(new java.awt.Color(27, 23, 51));
        jpnlPestañaAdministrarVuelos.setMinimumSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarVuelos.setPreferredSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarVuelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(30, 151, 196));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTRO DE MANTENIMIENTO");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 30));

        jpnlPestañaAdministrarVuelos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1090, 30));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarVuelos.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1090, 10));

        jtblTablaDeMantenimientos.setBackground(new java.awt.Color(217, 217, 217));
        jtblTablaDeMantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblTablaDeMantenimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTablaDeMantenimientosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblTablaDeMantenimientos);

        jpnlPestañaAdministrarVuelos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 130, 1090, 560));

        jlblNumeroDeOrdenes.setBackground(new java.awt.Color(102, 0, 51));
        jlblNumeroDeOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblNumeroDeOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        jlblNumeroDeOrdenes.setText("Numero de Registros: ");
        jlblNumeroDeOrdenes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpnlPestañaAdministrarVuelos.add(jlblNumeroDeOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 695, 220, 40));

        jbtnReiniciar.setBackground(new java.awt.Color(0, 102, 0));
        jbtnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReiniciar.setText("Actualizar");
        jpnlPestañaAdministrarVuelos.add(jbtnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 40));

        jbtnInfoOrden.setBackground(new java.awt.Color(102, 0, 51));
        jbtnInfoOrden.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInfoOrden.setText("Info. Orden");
        jbtnInfoOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInfoOrdenActionPerformed(evt);
            }
        });
        jpnlPestañaAdministrarVuelos.add(jbtnInfoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 160, 40));

        getContentPane().add(jpnlPestañaAdministrarVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblTablaDeMantenimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTablaDeMantenimientosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblTablaDeMantenimientosMouseClicked

    private void jbtnInfoOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInfoOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnInfoOrdenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtnInfoOrden;
    public javax.swing.JButton jbtnReiniciar;
    public javax.swing.JLabel jlblNumeroDeOrdenes;
    private javax.swing.JPanel jpnlPestañaAdministrarVuelos;
    public javax.swing.JTable jtblTablaDeMantenimientos;
    // End of variables declaration//GEN-END:variables
}
