/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vst.Herramienta;

import java.awt.Color;
import java.util.Date;

/**
 *
 * @author User
 */
public class VstHerramientaMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLibroNuevo
     */
    public VstHerramientaMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jtxtIDHerramienta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDescProblema = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jcbxEstado = new javax.swing.JComboBox<>();
        jdtcFechaCierre = new com.toedter.calendar.JDateChooser();
        jdtcFechaCreacion = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jtxtNombreHerramienta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtDescReparacion = new javax.swing.JTextArea();
        jcbxTipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jtxtNombreEmp = new javax.swing.JTextField();
        jspnCostoReparacion = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Herramienta Nueva");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(27, 23, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mantenimiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha de Cierre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 180, 50));

        jtxtIDHerramienta.setBackground(new java.awt.Color(217, 217, 217));
        jtxtIDHerramienta.setForeground(new java.awt.Color(153, 153, 153));
        jtxtIDHerramienta.setEnabled(false);
        jtxtIDHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtIDHerramientaMousePressed(evt);
            }
        });
        jtxtIDHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIDHerramientaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtIDHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 50, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Creacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Problema:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, -1));

        jtxtDescProblema.setBackground(new java.awt.Color(217, 217, 217));
        jtxtDescProblema.setColumns(20);
        jtxtDescProblema.setRows(5);
        jtxtDescProblema.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jtxtDescProblema);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 320, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Empleado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Costo Reparacion (S/):");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 140, -1));

        btnGuardar.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 180, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 10, 320));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Estado:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 130, -1));

        jcbxEstado.setBackground(new java.awt.Color(217, 217, 217));
        jcbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EN PROCESO", "FINALIZADO" }));
        jcbxEstado.setEnabled(false);
        jPanel1.add(jcbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 140, 40));

        jdtcFechaCierre.setDateFormatString("yyyy-MM-dd");
        jdtcFechaCierre.setMaxSelectableDate(new java.util.Date(253370786512000L));
        jdtcFechaCierre.setMinSelectableDate(new Date());
        jdtcFechaCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdtcFechaCierreMousePressed(evt);
            }
        });
        jPanel1.add(jdtcFechaCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 72, 150, 40));

        jdtcFechaCreacion.setDateFormatString("yyyy-MM-dd");
        jdtcFechaCreacion.setMaxSelectableDate(new java.util.Date(253370786512000L));
        jdtcFechaCreacion.setMinSelectableDate(new Date());
        jdtcFechaCreacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jdtcFechaCreacionMousePressed(evt);
            }
        });
        jPanel1.add(jdtcFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 72, 150, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 250, -1));

        jtxtNombreHerramienta.setBackground(new java.awt.Color(217, 217, 217));
        jtxtNombreHerramienta.setForeground(new java.awt.Color(153, 153, 153));
        jtxtNombreHerramienta.setEnabled(false);
        jtxtNombreHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtNombreHerramientaMousePressed(evt);
            }
        });
        jtxtNombreHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreHerramientaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtNombreHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 250, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reparacion:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, -1));

        jtxtDescReparacion.setBackground(new java.awt.Color(217, 217, 217));
        jtxtDescReparacion.setColumns(20);
        jtxtDescReparacion.setRows(5);
        jtxtDescReparacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jtxtDescReparacion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 320, -1));

        jcbxTipo.setBackground(new java.awt.Color(217, 217, 217));
        jcbxTipo.setEnabled(false);
        jPanel1.add(jcbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 130, -1));

        jtxtNombreEmp.setBackground(new java.awt.Color(217, 217, 217));
        jtxtNombreEmp.setEnabled(false);
        jtxtNombreEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNombreEmpKeyPressed(evt);
            }
        });
        jPanel1.add(jtxtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, 40));
        jPanel1.add(jspnCostoReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIDHerramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIDHerramientaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDHerramientaMousePressed

    private void jtxtIDHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDHerramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDHerramientaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jdtcFechaCierreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdtcFechaCierreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdtcFechaCierreMousePressed

    private void jdtcFechaCreacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdtcFechaCreacionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdtcFechaCreacionMousePressed

    private void jtxtNombreHerramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNombreHerramientaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreHerramientaMousePressed

    private void jtxtNombreHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreHerramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreHerramientaActionPerformed

    private void jtxtNombreEmpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreEmpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreEmpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstHerramientaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstHerramientaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstHerramientaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstHerramientaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstHerramientaMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JComboBox<String> jcbxEstado;
    public javax.swing.JComboBox<String> jcbxTipo;
    public com.toedter.calendar.JDateChooser jdtcFechaCierre;
    public com.toedter.calendar.JDateChooser jdtcFechaCreacion;
    public javax.swing.JSpinner jspnCostoReparacion;
    public javax.swing.JTextArea jtxtDescProblema;
    public javax.swing.JTextArea jtxtDescReparacion;
    public javax.swing.JTextField jtxtIDHerramienta;
    public javax.swing.JTextField jtxtNombreEmp;
    public javax.swing.JTextField jtxtNombreHerramienta;
    // End of variables declaration//GEN-END:variables
}
