/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vst.Reporte;

import Vst.Reporte.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author admin
 */
public class VstReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form prueba
     */
    public VstReportes() {
        initComponents();       
      
        jTabbedPane2.setEnabledAt(0, true);
        jTabbedPane2.setEnabledAt(1, true);
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPestañaAdministrarUsuarios = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_reporteAlquiler = new javax.swing.JTable();
        fecha_desde = new com.toedter.calendar.JDateChooser();
        totalRecaudado = new javax.swing.JLabel();
        total_hAlquiladas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fecha_hasta = new com.toedter.calendar.JDateChooser();
        btn_reportePorFecha = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reporteOtros = new javax.swing.JTable();
        btn_reporte2 = new javax.swing.JButton();
        btn_reporte3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fecha_desde1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        fecha_hasta1 = new com.toedter.calendar.JDateChooser();
        jLabel_descripcion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnlPestañaAdministrarUsuarios.setBackground(new java.awt.Color(27, 23, 51));
        jpnlPestañaAdministrarUsuarios.setPreferredSize(new java.awt.Dimension(930, 490));
        jpnlPestañaAdministrarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnlPestañaAdministrarUsuarios.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 1090, 10));

        jTabbedPane2.setBackground(new java.awt.Color(27, 23, 51));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(27, 23, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1060, 735));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_reporteAlquiler.setBackground(new java.awt.Color(217, 217, 217));
        tabla_reporteAlquiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla_reporteAlquiler);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1050, 460));
        jPanel3.add(fecha_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 180, 30));

        totalRecaudado.setBackground(new java.awt.Color(102, 0, 51));
        totalRecaudado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalRecaudado.setForeground(new java.awt.Color(255, 255, 255));
        totalRecaudado.setText("Total recaudado:");
        totalRecaudado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(totalRecaudado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 290, 30));

        total_hAlquiladas.setBackground(new java.awt.Color(102, 0, 51));
        total_hAlquiladas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total_hAlquiladas.setForeground(new java.awt.Color(255, 255, 255));
        total_hAlquiladas.setText("Total de herramientas alquiladas:");
        total_hAlquiladas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(total_hAlquiladas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 290, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hasta");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desde");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));
        jPanel3.add(fecha_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 180, 30));

        btn_reportePorFecha.setText("Generar reporte");
        btn_reportePorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportePorFechaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_reportePorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 140, 30));

        jTabbedPane2.addTab("Reporte de alquiler por fecha especificada", jPanel3);

        jPanel1.setBackground(new java.awt.Color(27, 23, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_reporteOtros.setBackground(new java.awt.Color(217, 217, 217));
        tabla_reporteOtros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_reporteOtros);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 1040, 200));

        btn_reporte2.setText("Mostrar las 10 herramientas que mas ingresos generaron ");
        jPanel1.add(btn_reporte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 380, 60));

        btn_reporte3.setText("Mostrar herramientas que nunca se  alquilaron");
        jPanel1.add(btn_reporte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 390, 60));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desde");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));
        jPanel1.add(fecha_desde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 180, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hasta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));
        jPanel1.add(fecha_hasta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 180, 30));

        jLabel_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_descripcion.setText("descripcion");
        jPanel1.add(jLabel_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 630, -1));

        jTabbedPane2.addTab("Otros", null, jPanel1, "");

        jpnlPestañaAdministrarUsuarios.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1080, 670));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(51, 0, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REPORTES");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 30));

        jpnlPestañaAdministrarUsuarios.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1070, 30));

        getContentPane().add(jpnlPestañaAdministrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -1, 1110, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reportePorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportePorFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportePorFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_reporte2;
    public javax.swing.JButton btn_reporte3;
    public javax.swing.JButton btn_reportePorFecha;
    public com.toedter.calendar.JDateChooser fecha_desde;
    public com.toedter.calendar.JDateChooser fecha_desde1;
    public com.toedter.calendar.JDateChooser fecha_hasta;
    public com.toedter.calendar.JDateChooser fecha_hasta1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel_descripcion;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JPanel jpnlPestañaAdministrarUsuarios;
    public javax.swing.JTable tabla_reporteAlquiler;
    public javax.swing.JTable tabla_reporteOtros;
    public javax.swing.JLabel totalRecaudado;
    public javax.swing.JLabel total_hAlquiladas;
    // End of variables declaration//GEN-END:variables
}
